version: '1.0.{build}'

branches:
  except:
    - gh-pages

image: Visual Studio 2017

clone_folder: c:\projects\

platform: Any CPU

configuration: Debug

build:
  parallel: true
  project: solutions\oes-all.sln
  verbosity: minimal

install:
  - nuget restore solutions\oes-all.sln

test_script:
  - cd C:\projects\
  - cmd: .\coverage.cmd 